// This file was generated by Prisma, and assumes you run Prisma commands using `bun --bun run prisma [command]`.
import { defineConfig, env, PrismaConfig } from "prisma/config";
import "dotenv/config"; // Ensure local environment parameters route into module boundaries

export default defineConfig({
  schema: "prisma/",
  migrations: {
    path: "prisma/migrations",
    seed: "bun prisma/seed.ts",
  },
  datasource: {
    // Falls back to system/runtime environment or dummy targets if file-level resolution fails
    url: env("DATABASE_URL") || process.env.DATABASE_URL || "postgresql://dummy:dummy@localhost:5432/dummy",
  },
}) satisfies PrismaConfig;
